---
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tópicos Avanzados de Series Cronológicas

Profesor: Shu Wei Chou Chen (shuwei.chou@ucr.ac.cr)

## DESCRIPCION:

El presente es un curso teórico-práctico que proporciona al estudiantado los métodos avanzados del análisis de series cronológicas.

Este curso es una continuación del primer curso de series cronológicas, el cual abarca principalmente análisis de series temporales estacionarias y univariadas. En la práctica, las series observadas generalmente no son estacionarias, y además, es común enfrentar situaciones que presentan series temporales multivariadas. Este curso pretende profundizar los conceptos del primer curso, y proporciona herramientas avanzadas para realizar análisis y pronósticos de series temporales univariadas y multivariadas en diversas áreas de aplicaciones.

[Programa del curso](https://shuwei325.github.io/SP2600-I22/SP2600-programa.pdf)

Las clases grabadas se encuentran [aquí](https://youtube.com/playlist?list=PL81c0Y-B3uz1Vf_SsNyqssyX6QAhphXFB) 

Semana        | Presentaciones | Laboratorio y Materiales extras
------------- | -------------- | ------------
1             | [Clase 1](https://shuwei325.github.io/SP2600-I22/clase01.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab01.R)
2             | [Clase 2](https://shuwei325.github.io/SP2600-I22/clase02.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab02.R)  
3             | Semana Santa   |
3             | [Clase 3](https://shuwei325.github.io/SP2600-I22/clase03.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab03.R)  
4             | [Clase 4](https://shuwei325.github.io/SP2600-I22/clase04.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab04.R)  
5             | [Clase 5](https://shuwei325.github.io/SP2600-I22/clase05.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab05.R)  
6             | [Clase 6](https://shuwei325.github.io/SP2600-I22/clase06.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab06.rar)  
7             | [Clase 7](https://shuwei325.github.io/SP2600-I22/clase07.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab07.R)  
8             | [Clase 8](https://shuwei325.github.io/SP2600-I22/clase08.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab08.R)  
9             | [Clase 9](https://shuwei325.github.io/SP2600-I22/clase09.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab09.R)  
10            | [Clase 10](https://shuwei325.github.io/SP2600-I22/clase10.html) |    |
11            | [Clase 11](https://shuwei325.github.io/SP2600-I22/clase11.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab10.R)  
12            | Exposiciones|[lab](https://shuwei325.github.io/SP2600-I22/lab11.R)  
13            | [Clase 13](https://shuwei325.github.io/SP2600-I22/clase13.html) |    |
14            | [Clase 14](https://shuwei325.github.io/SP2600-I22/clase14.html)|[lab](https://shuwei325.github.io/SP2600-I22/lab12.R)  






